blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
app_name='blog'
urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'create_blog/',views.create_blog),
    url(r'^$', views.home, name='home',),
    url(r'^(?P<slug>[-\w]+)/$', views.entry, name='entry'),
    url(r'^categories/(?P<pk>\d+)/$', views.category_topics, name='category_topics'),
    url(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.topic_posts, name='topic_posts'),
    #url(r'^(?P<pk>\d+)/comment/(?P<topic_pk>\d+)/$', views.comment),
    url(r'^add_comment/$',views.comment,name='comments'),
    #url(r'^tinymce/$', include('tinymce.urls')), 
    url(r'^title/(?P<pk>\d+)/$', views.get_title, name='get_title'),
]

blog_project/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from blog_project import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index,name='homepage' ),
    url(r'^tinymce/', include('tinymce.urls')),

    url(r'^blog/', include('blog.urls',namespace='blog')),
    url(r'^videoapp/', include('videoapp.urls', namespace='videoapp')),
    url(r'^gkapp/', include('gk_app.urls', namespace='gk_app')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^jobs/', include('jobs.urls',namespace='jobs')),
    url(r'^question/', include('question_bank.urls',namespace='question_bank')),

    url(r'^api/', include('news.api.urls')),
    url(r'^api/blog/', include('blog.api.urls')),
    url(r'^api/jobs/', include('jobs.api.urls')),
    url(r'^api/video/', include('videoapp.api.urls')),

    url(r'^api/question/', include('question_bank.api.urls'))
]

jobs/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from jobs import views
app_name="jobs"
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'create_blog/',views.create_blog),
    url(r'^$', views.home, name='home',),
    url(r'^categories/(?P<pk>\d+)/$', views.category_topics, name='category_topics'),
    url(r'^kkcate2/(?P<pk>\d+)/$', views.categoryWise_topics, name='category_topics2'),
    url(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.topic_posts, name='topic_posts'),
    url(r'^(?P<pk>\d+)/topics2/(?P<topic_pk>\d+)/$', views.topic_posts2, name='topic_posts2'),

    #url(r'^(?P<pk>\d+)/comment/(?P<topic_pk>\d+)/$', views.comment),
    #url(r'^comment/$',views.comment),
    #url(r'^tinymce/', include('tinymce.urls'))
]

news/api/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^news/$',views.NewsDetailAPIView.as_view(),name='NewsDetail'),
    url(r'^datewiseNews/$',views.DateWiseNewsDetailsAPIView.as_view(),name='date'),
    url(r'^categoryNews/$',views.CatogoryWiseNewsDetailsAPIView.as_view(),name='Newscategory'),
    ]

news/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from news import views
app_name='news'
urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^hindi/', views.hindi, name="hindi"),

]

news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.utils.text import Truncator
import datetime
class News(models.Model):
    news_text = models.TextField(blank=True)
    hindi_news=models.TextField(blank=True)
    title = models.CharField(max_length=200,blank=True)
    title_hindi = models.CharField(max_length=200, blank=True)
    category = models.CharField(max_length=200,blank=True,default="Editorial")
    source = models.CharField(max_length=200, blank=True,default="The Hindu")
    date=models.DateField(default=datetime.date.today,null=True, blank=True)
    link1 = models.URLField(null=True, blank=True)
    language=models.CharField(max_length=200,blank=True,default="English")
    def __str__(self):
        return self.title

news/api/views.py
from rest_framework import generics
from django.utils import timezone
#:from celery.result import AsyncResult 
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from news.models import *
from django.http import Http404, HttpResponse
from .serializers import *

import json
import random
from rest_framework.response import Response
from rest_framework.permissions import (
    IsAuthenticated
)

import datetime
from decimal import Decimal




class NewsDetailAPIView(APIView):
    #serializer_class = NewsSerializer
    def get(self, request, format=None):
        news_content =News.objects.all()   
        category_list=[]
        title_list=[]
        hindi_titles=[]
        hindi_new=[]
        content_list=[]
        date_list=[]
        source_list=[]
        link_list=[]
        for i in news_content:
            category=i.category
            title=i.title
            text= i.news_text
            dates=i.date
            sources=i.source
            links=i.link1
            hindi_ti=i.title_hindi
            hindi_content=i.hindi_news

            category_list.append(category)
            title_list.append(title)
            content_list.append(text)
            date_list.append(dates)
            source_list.append(sources)
            link_list.append(links)
            hindi_titles.append(hindi_ti)
            hindi_new.append(hindi_content)
        # #print('post api working')
        # print(len(title_list))
        # print(len(content_list))
        contents=list(zip(category_list,title_list,date_list,source_list,link_list,content_list,hindi_titles,hindi_new))
        final_news = []
        for a,b,c,d,e,f,g,h in contents:
            dict = {'category':a,'English_title':b,"Hindi_title":g,'date':c,'source':d,'link':e,'English_news':f,"Hindi_news":h}
            final_news.append(dict)
             #print(type(i))
             #context = {"date":date,"news_content":i}
         #print(len(dict))
        context={'news':final_news}
        return Response(context)


class DateWiseNewsDetailsAPIView(APIView):
    def post(self,request,*args,**kwargs):
        date = request.POST['date']
        print(date)
        dateWiseNews= News.objects.filter(date=date)
        #news_content = News.objects.all()
        #serialzer = NewsSerializer(dateWiseNews, many=True)
        #return Response(serialzer.data)
        category_list=[]
        title_list=[]
        content_list=[]
        date_list=[]
        source_list=[]
        link_list=[]
        hindi_titles = []
        hindi_new = []

        for i in dateWiseNews:
            category=i.category
            title=i.title
            text= i.news_text
            dates=i.date
            sources=i.source
            links=i.link1
            hindi_ti = i.title_hindi
            hindi_content = i.hindi_news

            category_list.append(category)
            title_list.append(title)
            content_list.append(text)
            date_list.append(dates)
            source_list.append(sources)
            link_list.append(links)
            hindi_titles.append(hindi_ti)
            hindi_new.append(hindi_content)

        # #print('post api working')
        # print(len(title_list))
        # print(len(content_list))
        contents = list(
            zip(category_list, title_list, date_list, source_list, link_list, content_list, hindi_titles, hindi_new))
        final_news = []
        for a, b, c, d, e, f, g, h in contents:
            dict = {'category': a, 'English_title': b, "Hindi_title": g, 'date': c, 'source': d, 'link': e,
                    'English_news': f, "Hindi_news": h}
            final_news.append(dict)
            # print(type(i))
            # context = {"date":date,"news_content":i}
        # print(len(dict))
        context = {'news': final_news}
        return Response(context)


class CatogoryWiseNewsDetailsAPIView(APIView):
    def post(self,request,*args,**kwargs):
        category_name = request.POST['category']
        CategoryWiseNews= News.objects.filter(category=category_name)
        category_list=[]
        title_list=[]
        content_list=[]
        date_list=[]
        source_list=[]
        link_list=[]
        hindi_titles = []
        hindi_new = []

        for i in CategoryWiseNews:
            category=i.category
            title=i.title
            text= i.news_text
            dates=i.date
            sources=i.source
            links=i.link1
            hindi_ti = i.title_hindi
            hindi_content = i.hindi_news


            category_list.append(category)
            title_list.append(title)
            content_list.append(text)
            date_list.append(dates)
            source_list.append(sources)
            link_list.append(links)
            hindi_titles.append(hindi_ti)
            hindi_new.append(hindi_content)


        # #print('post api working')
        # print(len(title_list))
        # print(len(content_list))

        contents = list(
            zip(category_list, title_list, date_list, source_list, link_list, content_list, hindi_titles, hindi_new))
        final_news = []
        for a, b, c, d, e, f, g, h in contents:
            dict = {'category': a, 'English_title': b, "Hindi_title": g, 'date': c, 'source': d, 'link': e,
                    'English_news': f, "Hindi_news": h}
            final_news.append(dict)
            # print(type(i))
            # context = {"date":date,"news_content":i}
        # print(len(dict))
        context = {'news': final_news}
        return Response(context)

    

news/views.py
from django.shortcuts import render
from .models import *
#from news.scarpdata import *
from django.contrib.auth.models import User, Group
#from news.theHinduEditorial import *
#from news.latest_Editorial import *
#
# Create your views here
import datetime
def home(request):

          try:
               #news_list =list(zip(title_list,contents_list,final_category))
               #for title, text, cat in news_list:
               news_list=list(zip(titless_list,hindi_titles,contents, hindi_contents,dateInserted_list))
               for title,h_title,text,h_text,da in news_list:
                    entries=News()
                    entries.title= title
                    entries.title_hindi=h_title
                    entries.hindi_news=h_text
                    entries.news_text= text
                    #print(text)
                    #entries.category= cat
                    entries.date=datetime.date.today()
                    #print(entries.date)
                    entries.save()
                    print("hiii")
               entry = News.objects.all().order_by('id').reverse()
                    #datewise = News.objects.filter(date__gte=datetime.date.today())
                    #for post in datewise:
                    #print(post.news_text)
               return render(request,'news/index.html', {'entry': entry})
          except:
               print("coming in except")
               entry = News.objects.all().order_by('id').reverse()
               return render(request, 'news/index.html',{'entry':entry})

def hindi(request):
     entry = News.objects.all().order_by('id').reverse()
     return render(request, 'news/index2.html', {'entry': entry})

news/templates/news/index.html
<!DOCTYPE html>
{% extends 'newsapp/base.html' %}

{% load static %}
<html lang="en">

{% block title %}{{ entry.title }}{% endblock %}

<head>
<body>
<script>
var d = new Date();
document.getElementById("header").innerHTML = d;
</script>
</body>
<!--<link rel="icon" href="{% static 'gk_app/bodhi_logo.png'%}" type="image/gif" sizes="16x16">-->
 <style>


  }

</style>
<a href ="/CreateBlog/">New Blog</a>s
{% block breadcrumb %}
    <li  class="breadcrumb-item active"> <h3></h3></li>
{% endblock %}

{% block content %}
<button class="btn btn-default"> <a href="{% url 'news:hindi' %}">Hindi</a></button>
    <body>

<!--     <div class="col s3 simple" style="margin-left: px;padding-left:px;width: 26.66667%;">-->
<!--         <div class="panel-title" style="max_width:100%;font-size:18px;color: inherit;background-color: black;font-family: 'Raleway', sans-serif;color: #fff;padding:10px ;  position: sticky; top: -10px;">Date Wise Current Affair</div>-->
<!--         <div class="  " style="box-sizing: border-box;overflow-y: auto;max-height:400px;padding:10px; box-shadow: 1px 1px 1px 1px gray ; position: relative; ">-->



<!--     {% for category in categories %}-->

<!--      <div class="scrollbox" style="padding:10px; padding: 10px ; color: black ; border-bottom: solid #c5c0c0 1px;"> <a  class="scrollbox-content" style="padding-bottom:10px; margin-bottom: 5px ; text-decoration:none ; color:black;" href="{% url 'gk_app:category_topics' category.pk %}">{{category.name }} </a></div>-->

<!--      {% endfor %}-->

<!--</div>-->
<!--<br><br>-->
<!--              <div class="panel-title" style="max_width:100%;font-size:16px;color: inherit;background-color: #000000;font-family: 'Raleway', sans-serif;color: #fff;padding:10px ; margin-bottom: -8px ;  position: sticky; top: -10px;">Category Wise Current Affair</div>-->
<!--  <div class="  "style="box-sizing: border-box;overflow-y: auto;max-height:400px;padding:10px; box-shadow: 1px 1px 1px 1px gray ; position: relative; ">-->
<!--&lt;!&ndash;     <div class="panel-title" style="max_width:100%;font-size:16px;color: inherit;background-color: #000000;font-family: 'Raleway', sans-serif;color: #fff;padding:10px ; margin-bottom: -8px ;  position: sticky; top: -10px;">Category Wise Current Affair</div>&ndash;&gt;-->

<!--</br>-->

<!--     {% for c in GK_categories %}-->

<!--      <div class=" scrollbox  " style="padding:10px; padding: 10px ; color: black ; border-bottom: solid #c5c0c0 1px;">  <a  class="scrollbox-content" style="padding-bottom:10px; margin-bottom: 5px ; text-decoration:none ; color:black;" href="{% url 'gk_app:category_topics2' c.pk %}">{{c.name }} </a></div>-->
<!--        <small class="text-muted d-block">{{category.description }}  </small>-->

<!--      {% endfor %}-->

<!--    </div>-->

<!--    </div>-->
<!--</body>-->









 {% for e in entry %}
        {% if e.language == "English" %}
    <div class="card mb-2  border-dark" style="margin-top:25px;width: 100%;min-width: 350px;">
        <div class="  py-2 px-3 header" style="background-color:black" ><img src="{% static 'newsapp/bodhi_logo.png'%}" style="width:25px ; height:25px;border-radius: 100%;"alt="Avatar" ;> {{e.date}}
        </div>

        <div class="text">
        <div style= " border-radius: 50%;padding-left: 15%;">

            </div>

            <div style="padding:10 25 0 25;color: #d63c24;font-size: 20px;line-height: normal;outline: medium none;text-decoration: none;">
                {{ e.title}}:
            </div>
            <div style="font-size:16; padding:5 25 0 25">
             <p>{{ e.news_text|safe }}</p>

            </p>
</div>

    </div>
    </div>
{% endif %}
  {% endfor %}


{% endblock %}




</html>

news/templates/news/index2.html
<!DOCTYPE html>
{% extends 'newsapp/base.html' %}

{% load static %}
<html lang="en">

{% block title %}{{ entry.title }}{% endblock %}

<head>
<body>
<script>
var d = new Date();
document.getElementById("header").innerHTML = d;
</script>
</body>
<!--<link rel="icon" href="{% static 'gk_app/bodhi_logo.png'%}" type="image/gif" sizes="16x16">-->
 <style>


  }

</style>
<a href ="/CreateBlog/">New Blog</a>s
{% block breadcrumb %}
    <li  class="breadcrumb-item active"> <h3></h3></li>
{% endblock %}

{% block content %}
<a href="{% url 'news:home' %}">English</a>
    <body>

<!--     <div class="col s3 simple" style="margin-left: px;padding-left:px;width: 26.66667%;">-->
<!--         <div class="panel-title" style="max_width:100%;font-size:18px;color: inherit;background-color: black;font-family: 'Raleway', sans-serif;color: #fff;padding:10px ;  position: sticky; top: -10px;">Date Wise Current Affair</div>-->
<!--         <div class="  " style="box-sizing: border-box;overflow-y: auto;max-height:400px;padding:10px; box-shadow: 1px 1px 1px 1px gray ; position: relative; ">-->



<!--     {% for category in categories %}-->

<!--      <div class="scrollbox" style="padding:10px; padding: 10px ; color: black ; border-bottom: solid #c5c0c0 1px;"> <a  class="scrollbox-content" style="padding-bottom:10px; margin-bottom: 5px ; text-decoration:none ; color:black;" href="{% url 'gk_app:category_topics' category.pk %}">{{category.name }} </a></div>-->

<!--      {% endfor %}-->

<!--</div>-->
<!--<br><br>-->
<!--              <div class="panel-title" style="max_width:100%;font-size:16px;color: inherit;background-color: #000000;font-family: 'Raleway', sans-serif;color: #fff;padding:10px ; margin-bottom: -8px ;  position: sticky; top: -10px;">Category Wise Current Affair</div>-->
<!--  <div class="  "style="box-sizing: border-box;overflow-y: auto;max-height:400px;padding:10px; box-shadow: 1px 1px 1px 1px gray ; position: relative; ">-->
<!--&lt;!&ndash;     <div class="panel-title" style="max_width:100%;font-size:16px;color: inherit;background-color: #000000;font-family: 'Raleway', sans-serif;color: #fff;padding:10px ; margin-bottom: -8px ;  position: sticky; top: -10px;">Category Wise Current Affair</div>&ndash;&gt;-->

<!--</br>-->

<!--     {% for c in GK_categories %}-->

<!--      <div class=" scrollbox  " style="padding:10px; padding: 10px ; color: black ; border-bottom: solid #c5c0c0 1px;">  <a  class="scrollbox-content" style="padding-bottom:10px; margin-bottom: 5px ; text-decoration:none ; color:black;" href="{% url 'gk_app:category_topics2' c.pk %}">{{c.name }} </a></div>-->
<!--        <small class="text-muted d-block">{{category.description }}  </small>-->

<!--      {% endfor %}-->

<!--    </div>-->

<!--    </div>-->
<!--</body>-->









 {% for e in entry %}

    <div class="card mb-2  border-dark" style="margin-top:25px;width: 100%;min-width: 350px;">
        <div class="  py-2 px-3 header" style="background-color:black" ><img src="{% static 'newsapp/bodhi_logo.png'%}" style="width:25px ; height:25px;border-radius: 100%;"alt="Avatar" ;> {{e.date}}
        </div>

        <div class="text">
        <div style= " border-radius: 50%;padding-left: 15%;">

            </div>

            <div style="padding:10 25 0 25;color: #d63c24;font-size: 20px;line-height: normal;outline: medium none;text-decoration: none;">
                {{ e.title_hindi}}:
            </div>
            <div style="font-size:16; padding:5 25 0 25">
             <p>{{ e.hindi_news|safe }}</p>

            </p>
</div>

    </div>
    </div>


  {% endfor %}


{% endblock %}




</html>