blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
app_name='blog'
urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'create_blog/',views.create_blog),
    url(r'^$', views.home, name='home',),
    url(r'^(?P<slug>[-\w]+)/$', views.entry, name='entry'),
    url(r'^categories/(?P<pk>\d+)/$', views.category_topics, name='category_topics'),
    url(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.topic_posts, name='topic_posts'),
    #url(r'^(?P<pk>\d+)/comment/(?P<topic_pk>\d+)/$', views.comment),
    url(r'^add_comment/$',views.comment,name='comments'),
    #url(r'^tinymce/$', include('tinymce.urls')), 
    url(r'^title/(?P<pk>\d+)/$', views.get_title, name='get_title'),
]

blog_project/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from blog_project import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index,name='homepage' ),
    url(r'^tinymce/', include('tinymce.urls')),

    url(r'^blog/', include('blog.urls',namespace='blog')),
    url(r'^videoapp/', include('videoapp.urls', namespace='videoapp')),
    url(r'^gkapp/', include('gk_app.urls', namespace='gk_app')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^jobs/', include('jobs.urls',namespace='jobs')),
    url(r'^question/', include('question_bank.urls',namespace='question_bank')),

    url(r'^api/', include('news.api.urls')),
    url(r'^api/blog/', include('blog.api.urls')),
    url(r'^api/jobs/', include('jobs.api.urls')),
    url(r'^api/video/', include('videoapp.api.urls')),

    url(r'^api/question/', include('question_bank.api.urls'))
]

videoapp/api/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^video/$',views.VideoDetailAPIView.as_view(),name='Video'),
    url(r'^topic_wise_video/$',views.TopicWiseVideoDetailsAPIView.as_view(),name='topice_video'),
    url(r'^category_wise_video/$',views.CategoryWiseVideoDetailsAPIView.as_view(),name='category_video'),
    ]

videoapp/urls.py
from django.conf.urls import url
from videoapp import views
app_name = 'videoapp'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<id>[-\w]+)/$', views.entry, name='entry'),
    url(r'^categories/(?P<pk>\d+)/$', views.category_topics, name='category_topics'),
    url(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.topic_posts, name='topic_posts'),

    #url(r'^title/(?P<pk>\d+)/$', views.get_title, name='get_title'),


]

videoapp/models.py
from django.db import models

# Create your models here.
# coding: utf-8

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    #description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey(Category,on_delete=models.CASCADE, related_name='topics1')
    Publisher = models.ForeignKey(User,on_delete=models.CASCADE,related_name='topics1')

    def __str__(self):
        return self.subject


class Video_Content(models.Model):
    Video_Content= models.TextField(max_length=4000)
    title = models.CharField(max_length=200,blank=True)
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE, related_name='posts1')
    #created_at = models.DateTimeField(auto_now_add=True,blank=True)
    updated_at = models.DateTimeField(null=True,blank=True,auto_now_add=True)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE, related_name='posts1',null=True,default="BodhiAI")
    #updated_by = models.ForeignKey(User,on_delete=models.CASCADE,null=True, related_name='+')
    link1 = models.URLField(null=True, blank=True)
    link2 = models.URLField(null=True, blank=True)
    link3 = models.URLField(null=True, blank=True)
    def __str__(self):
        return self.Video_Content



class Entry(models.Model):

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, null=True, blank=True)
    content = models.TextField(max_length=4000, null=True, blank=True)
    summary = models.TextField(null=True, blank=True)
    start_publication = models.DateTimeField(null=True, blank=True)
    created_by = models.CharField(max_length=255,null=True,default="bodhiai1")
    creation_date = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)

    link1 = models.URLField(null=True, blank=True)
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Entry"
        verbose_name_plural = "Entries"

    def __unicode__(self):
        return self.title

class Video(models.Model):
    #slug = models.SlugField(max_length=255, null=True, blank=True)
    content= models.TextField(max_length=4000)
    video_category= models.CharField(max_length=200,blank=True)
    video_topic = models.CharField(max_length=200,blank=True)
    video_title = models.CharField(max_length=200,blank=True)
    upload_date = models.DateTimeField(null=True,blank=True)
    #publisher = models.ForeignKey(User,on_delete=models.CASCADE, related_name='video',null=True,default="BodhiAI")
    publisher=models.CharField(max_length=200,default="BodhiAI",null=True,blank=True)
    #updat:xed_by = models.ForeignKey(User,on_delete=models.CASCADE,null=True, related_name='+')
    link1 = models.URLField(null=True, blank=True)
    link2 = models.URLField(null=True, blank=True)
    link3 = models.URLField(null=True, blank=True)
    def __str__(self):
        return self.video_title

videoapp/api/views.py
from rest_framework import generics
from django.utils import timezone
#:from celery.result import AsyncResult 
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from jobs.models import *
from django.http import Http404, HttpResponse
from .serializers import *

import json
import random
from rest_framework.response import Response
from rest_framework.permissions import (
    IsAuthenticated
)

import datetime
from decimal import Decimal


from django.contrib.auth.models import User


class VideoDetailAPIView(APIView):
    def get(self, request, format=None):
        video_content =Video.objects.all()
        #serialzer = VideoSerializer(video_content,many=True)
        #return Response(serialzer.data)
        print('hiii')
        publisher=[]
        content_list=[]
        category_list=[]
        title_list=[]
        topic_list=[]
        date_list=[]
        link1_list=[]
        link2_list=[]
        link3_list=[]

        for p in video_content:
            category=p.video_category
            topic=p.video_topic
            title=p.video_title
            upload_date=p.upload_date
            text=p.content
            link1=p.link1
            link2=p.link2
            link3=p.link3
            pub=p.publisher
            content_list.append(text)
            category_list.append(category)
            title_list.append(title)
            topic_list.append(topic)
            date_list.append(upload_date)
            link1_list.append(link1)
            link2_list.append(link2)
            link3_list.append(link3)
            publisher.append(pub)
            #print('api working')
        video_content=zip(category_list,topic_list,title_list,date_list,link1_list,link2_list,link3_list,content_list,publisher)
        video_list=[]
        for a,b,c,d,e,f,g,h,i in video_content:
            dict = {'category':a,'topic':b,'title':c,'date':d,'link1':e,'link2':f,'link3':g,'content':h,'publisher':i}
            video_list.append(dict)
        context={'video_content':video_list}
        return Response(context)


"""

class CategoryWiseVideoDetailsAPIView(APIView):
    def post(self,request,*args,**kwargs):
        video_category = request.POST['video_category']
        print(video_category)
        categoryWisevideo= Video.objects.filter(video_category=video_category)
        serialzer = VideoSerializer(categoryWisevideo,many=True)
        return Response(serialzer.data)

"""

class CategoryWiseVideoDetailsAPIView(APIView):
    def post(self,request,*args,**kwargs):
        video_category = request.POST['video_category']
        print(video_category)
        categoryWisevideo= Video.objects.filter(video_category=category)
        print('hiii')
        publisher=[]
        content_list=[]
        category_list=[]
        title_list=[]
        topic_list=[]
        date_list=[]
        link1_list=[]
        link2_list=[]
        link3_list=[]

        for p in categoryWisevideo:
            category=p.video_category
            topic=p.video_topic
            title=p.video_title
            upload_date=p.upload_date
            text=p.content
            link1=p.link1
            link2=p.link2
            link3=p.link3
            pub=p.publisher
            content_list.append(text)
            category_list.append(category)
            title_list.append(title)
            topic_list.append(topic)
            date_list.append(upload_date)
            link1_list.append(link1)
            link2_list.append(link2)
            link3_list.append(link3)
            publisher.append(pub)
            #print('api working')
        video_content=zip(category_list,topic_list,title_list,date_list,link1_list,link2_list,link3_list,content_list)
        video_list=[]
        for a,b,c,d,e,f,g,h in video_content:
            dict = {'category':a,'topic':b,'title':c,'date':d,'link1':e,'link2':f,'link3':g,'content':h}
            video_list.append(dict)
        context={'video_content':video_list}
        return Response(context)










"""
class TopicWiseVideoDetailsAPIView(APIView):
    def post(self,request,*args,**kwargs):
        video_topic = request.POST['video_topic']
        print(video_topic)
        topicWiseVideo= Video.objects.filter(video_topic=video_topic)
        serialzer = VideoSerializer(topicWiseVideo,many=True)
        return Response(serialzer.data)
"""





class TopicWiseVideoDetailsAPIView(APIView):
    def post(self,request,*args,**kwargs):
        video_topic = request.POST['topic']
        print(video_topic)
        topicWiseVideo= Video.objects.filter(video_topic=video_topic)

        print('hiii')
        publisher=[]
        content_list=[]
        category_list=[]
        title_list=[]
        topic_list=[]
        date_list=[]
        link1_list=[]
        link2_list=[]
        link3_list=[]

        for p in topicWiseVideo:
            category=p.video_category
            topic=p.video_topic
            title=p.video_title
            upload_date=p.upload_date
            text=p.content
            link1=p.link1
            link2=p.link2
            link3=p.link3
            pub=p.publisher
            content_list.append(text)
            category_list.append(category)
            title_list.append(title)
            topic_list.append(topic)
            date_list.append(upload_date)
            link1_list.append(link1)
            link2_list.append(link2)
            link3_list.append(link3)
            publisher.append(pub)
            #print('api working')
        video_content=zip(category_list,topic_list,title_list,date_list,link1_list,link2_list,link3_list,content_list)
        video_list=[]
        for a,b,c,d,e,f,g,h in video_content:
            dict = {'category':a,'topic':b,'title':c,'date':d,'link1':e,'link2':f,'link3':g,'content':h}
            video_list.append(dict)
        context={'video_content':video_list}
        return Response(context)

videoapp/views.py
from django.template.defaultfilters import slugify
from django.shortcuts import get_object_or_404, render,redirect
from .models import *
#from .video import *


"""
def home(request):

    try:
        video_list = list(zip(title_list,video_url,thumbnail_list,published_list))

        for i in video_list:
            entries = Video()
            entries.video_title = i[0]
            entries.content = i[1]
            entries.link1 = i[2]
            entries.save()
            print("hiii")
        entry = Video.objects.all().order_by('id').reverse()

        return render(request, 'videoapp/homepage111.html', {'entries': entry})
    except:
        print("coming in except")
        entry = Video.objects.all().order_by('id').reverse()
        return render(request, 'videoapp/homepage111.html', {'entries': entry})

"""
def home(request):

    try:
        video_list = list(zip(title_list,video_url,thumbnail_list,published_list))

        for i in video_list:
            entries = Entry()
            entries.title = i[0]
            entries.summary = i[1]

            entries.link1 = i[2]

            #entries.slug=i.pk
            slug_str = "%s" % (i[0].lower())
            entries.slug = slugify(slug_str)
            entries.created_by=request.user
            entries.save()
            print("hiii")
        entry = Entry.objects.all().order_by('id').reverse()

        return render(request, 'videoapp/homepage111.html', {'entries': entry})
    except:
        print("coming in except")
        entry = Entry.objects.all().order_by('id').reverse()
        return render(request, 'videoapp/homepage111.html', {'entries': entry})


def entry(request,id):
    blog_entry = get_object_or_404(Entry,id=id)
    return render(request, 'videoapp/entry.html', { 'entry': blog_entry })






# def home(request):
#     categories =Category.objects.all().order_by('id').reverse()
#     blogs = Video_Content.objects.all().order_by('updated_at').reverse()
#     entries = Entry.objects.filter(status=Entry.PUBLISHED).order_by('last_update').reverse()
#
#     return render(request,'videoapp/homepage.html', {'categories': categories,'blogs':blogs,'entries': entries })

def category_topics(request,pk):
    category = get_object_or_404(Category, pk=pk)
    topics = category.topics1.order_by('-last_updated').reverse()
    print("hiiii")
    return render(request, 'videoapp/topics.html', {'category': category, 'topics': topics})
def topic_posts(request, pk, topic_pk):
    topic =get_object_or_404(Topic, category__pk=pk, pk=topic_pk)
    topic.save()
    return render(request, 'videoapp/topic_posts.html', {'topic': topic})
def get_title(request,id):
    print(request.POST.get('id'),False)
    title_id=request.POST['id']
    print(title_id)
    print ('hiii')
    if request.method == 'POST':
        #blogs=get_object_or_404(Blog,id=pk)
        blogs = Blog.objects.get(id=title_id)
        return render(request,'videoapp/title.html',{"blogs":blogs})

videoapp/templates/videoapp/base.html
{% load staticfiles %}
<html>
  <head>
    <body>


<style>
  .header{
  background-color:#1abb9c;
  color: white;
  font-weight: 600;
}
  }

</style>
     <link href="https://fonts.googleapis.com/css?family=Overlock" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <meta charset="utf-8">
    <title>{% block title %}BodhiAI Video Tutorial {% endblock %}</title>
    <link href="{% static "tinymce/css/prism.css" %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'videoapp/img/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'videoapp/img/css/app.css' %}">
    {% block stylesheet %}{% endblock %}
  </head>
  {% if user.is_authenticated %}
  <a href ="/create_blog/"></a>
  {% endif %}
  <body>
    {% block body %}

      <nav class="navbar navbar-expand-sm navbar-dark  header" style="background-color:orange" >
        <div class="container">

          <a class="navbar-brand" href="{% url 'videoapp:home' %}">Apogee Video Tutorial </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="mainMenu">

              <ul class="navbar-nav ml-auto">
                <button type="button" class="btn btn-danger" style="height:auto ;">
                <a class="navbar-brand" href="http://bodhiaireact.s3-website.ap-south-1.amazonaws.com/#/userregistration">Join Now </a> </button>
                <li class="nav-item dropdown">
          <!--        <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                  </a> -->
                  </div>
                </li>
              </ul>


          </div>
        </div>
      </nav>

      <div class="container">
        <ol class="breadcrumb my-4">
          {% block breadcrumb %}
          {% endblock %}
        </ol>
        {% block content %}
        {% endblock %}
      </div>
    {% endblock body %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <style>

</style>

  <script src="https://code.jquery.com/jquery-3.1.1.min.js"
          integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
          crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
   <script src="{% static "tinymce/js/prism.js" %}"></script>


<!--<div id="fixed-social">-->
  <!--<div>-->
    <!--<a href="http://www.facebook.com/sharer/sharer.php?u=http://13.234.37.98/blog/" class="fixed-facebook" target="_blank"><i class="fa fa-facebook"></i> <span>Facebook</span></a>-->
  <!--</div>-->
  <!--<div>-->
    <!--<a href="http://www.twitter.com/login/?url=http://www.bodhiai.in/membership/register/{{ request.get_full_path|urlencode }}" class="fixed-twitter" target="_blank"><i class="fa fa-twitter"></i> <span>Twitter</span></a>-->
  <!--</div>-->
  <!--<div>-->
    <!--<a href="http://www.linkedin.com/shareArticle?url=http://www.bodhiai.in/membership/register/{{ request.get_full_path|urlencode }}&title=<Favourate Blog>&summary=<Blog>&source=www.bodhiai.in" class="fixed-linkedin" target="_blank"><i class="fa fa-linkedin"></i> <span>LinkedIn</span></a>-->
  <!--</div>-->
  <!--<div>-->
    <!--<a href="#" class="fixed-instagrem" target="_blank"><i class="fa fa-instagram"></i> <span>Instagram</span></a>-->
  <!--</div>-->







<div id="fixed-social" style= "position: fixed;top: 500px;left:260px;">
  <div>
    <a href="http://www.facebook.com/sharer/sharer.php?u=http://13.127.54.121/videoapp/" class="fixed-facebook" target="_blank"><i class="fa fa-facebook"></i> <span>Facebook</span></a>
  </div>
  <div>
    <a href="http://www.twitter.com/login/?url=http://13.127.54.121/videoapp/{{ request.get_full_path|urlencode }}" class="fixed-twitter" target="_blank"><i class="fa fa-twitter"></i> <span>Twitter</span></a>
  </div>
  <div>
    <a href="http://www.linkedin.com/shareArticle?url=http://13.127.54.121/videoapp/{{ request.get_full_path|urlencode }}&title=<Favourate Blog>&summary=<Blog>&source=www.bodhiai.in" class="fixed-linkedin" target="_blank"><i class="fa fa-linkedin"></i> <span>LinkedIn</span></a>
  </div>
  <div>
  <a href="https://www.instagram.com/login/?url=http://13.127.54.121/videoapp/" class="fixed-instagrem" target="_blank"><i class="fa fa-instagram"></i> <span>Instagram</span></a>
  </div>
  <div>
  </div>













</div>





</body>
</html>

videoapp/templates/videoapp/entries.html
{% block fullwidthheader %}
  <div class="masthead">
    <h1>The Parsifal Blog</h1>
    <p>Find out the latest news on Parsifal</p>
  </div>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      {% for entry in entries %}
        <article>
          <h2><a href="{% url 'videoapp:entry' entry.slug %}">{{ entry.title }}</a></h2>
          <p class="text-muted">


          </p>
          <div class="content">

          <iframe width="420" height="345" src="{{entry.summary}">
</iframe>
          </div>
        </article>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

videoapp/templates/videoapp/entry.html
{% extends 'videoapp/base3.html' %}
{% load staticfiles %}

{% block title %}{{ entry.title }}{% endblock %}
<body>
<style>
  .iframe
  {height:1000px;
  }
</style>
{% block content %}
  <div class="row">
    <div class="col">

      <article class="single-entry" ">
        
        <div class="card">
<a id="play-video" href="#"></a><br />

<iframe id="video" width="420" height="315" src="{{entry.summary}}" frameborder="0" allowfullscreen></iframe>

        </div>
	 <h2 class="page-header">{{ entry.title }}</h2>

      </article>
    </div>
  </div>
{% endblock content %}
</body>

videoapp/templates/videoapp/home.html
{% extends 'videoapp/base.html' %}
{% load staticfiles %}
<head>



@media (min-width:768px) {
    .card-topics > .card
    {
        width: 29%;
        flex-wrap: wrap;
        flex: initial;
    }
}
<style>
   .morecontent {
   display: none;
}

</style>>
</head>
<a href ="/CreateBlog/">New Blog</a>

{% block content %}
    <body>
<br><br><br>  <br><br>
 <div class="row ">
     <div class="col-md-10 col-sm-12 js-collectable " >

             <div style="">
<div class="row">

 {% for entry in entries %}

        <div class="col-sm-12 col-md-6"  style="margin-bottom: 20;">

    <div class="card h-15" >
            <div class=" card topics" >

        </div>
            <div class="card" >
             <article>
          <a  style="font-family: 'initial', cursive;font-weight: 600; padding-left:10" href="{% url 'videoapp:entry' entry.slug %}">{{ entry.title }}</a>
          <div style="object-fit:contain" style="width:100%" class="content">
            {{ entry.summary|safe }}
          </div>
        </article>

             </div>



        <div class="text2"  >
        <div style= " border-radius: 50%;">

        <div style="display: inline-block; margin:5px ">

            </div>
            </div>


               <!--<a href="http://www.bodhiai.in/">-->

        <img src="{% static '/videoapp/bodhi_logo.png'%}" style="width:50px ; height:50px;border-radius: 100%;"alt="Avatar" ;>
           <div style="display: inline-block; margin:2px ">
            <div> BodhiAI </div>
            <div>  {{ entry.last_update.date }} </div>
             </div>
         </a>
        </div>



    </div>
</div>


              {% endfor %}
    </div>
         </div>

 </div>


      <body >
     <div class="col s3 simple" style="margin-left: 15px;padding-left:15px;width: 80.66667%; ">
         <div class="panel" style="width:167%;font-size:18px;color: inherit;background-color: black;font-family: 'Raleway', sans-serif;color: #fff;padding:10px ; margin-bottom: px ;  position: sticky; top: -10px;">Category Wise Videos</div>
         <div class="  " style="box-sizing: border-box;overflow-y: auto;max-height:400px;padding:10px; box-shadow: 1px 1px 1px 1px gray ; position: relative; width: 165%;">
      <div class="panel-title" style="max_width:0%;font-size:1px;color: inherit;font-family: 'Raleway', sans-serif;color: #fff   t;"></div>

     {% for category in categories %}

      <div class="scrollbox" style="padding:7px; padding: 7px ; width:100%;color: black ; border-bottom: solid #c5c0c0 1px;border-bottom-length: 100%;"> <a  class="force-overflow" style="padding-bottom:10px; margin-bottom: 5px ; text-decoration:none ; color:black;" href="{% url 'videoapp:category_topics' category.pk %}" >{{category.name }} </a></div>

      {% endfor %}








<!--<div class="col-2">-->
     <!--<div class="sidebars" style="width: 16.66667%;">-->
         <!--<h4>Categoy Wise Videos</h4>-->
      <!--<h1 class="latest"></h1>-->

    <!--{% for category in categories %}-->
    <!--<div class="sideblog" >-->
        <!--<div class="card-panel">-->
        <!--<a href="{% url 'videoapp:category_topics' category.pk %}" >{{category.name }}</a><br>-->
        <!--<small class="text-muted d-block">{{category.description }}</small>-->
    <!--</div>-->


      <!--{% endfor %}-->
    <!--</div>-->
        <!--</div>-->
    <!--</div>-->

    </div>
<body>








</div>

    </div>
	</body>



</body>

 {% endblock %}

videoapp/templates/videoapp/reply_topic.html
{% extends 'base.html' %}
{% block content %}
    {% for post in comments %}
        <pre> by {{ post.user }}
            {{ post.comment}}</pre>
    {% endfor %}
{% endblock %}
</html

videoapp/templates/videoapp/topics.html
{% extends 'videoapp/base.html' %}

{% block title %}
  {{ category.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'videoapp:home' %}">Categories</a></li>
  <li class="breadcrumb-item active">{{ categoy.name }}</li>
{% endblock %}

{% block content %}


  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Topic</th>
        <th>Publisher</th>
        <th>Publish Date</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in topics %}
        <tr>
          <td><a href="{% url 'videoapp:topic_posts' category.pk topic.pk %}">{{ topic.subject }}</a></td>
          <td>{{ topic.Publisher.username }}</td>
          <td>{{ topic.last_updated }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}