blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
app_name='blog'
urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'create_blog/',views.create_blog),
    url(r'^$', views.home, name='home',),
    url(r'^(?P<slug>[-\w]+)/$', views.entry, name='entry'),
    url(r'^categories/(?P<pk>\d+)/$', views.category_topics, name='category_topics'),
    url(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.topic_posts, name='topic_posts'),
    #url(r'^(?P<pk>\d+)/comment/(?P<topic_pk>\d+)/$', views.comment),
    url(r'^add_comment/$',views.comment,name='comments'),
    #url(r'^tinymce/$', include('tinymce.urls')), 
    url(r'^title/(?P<pk>\d+)/$', views.get_title, name='get_title'),
]

blog_project/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from blog_project import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index,name='homepage' ),
    url(r'^tinymce/', include('tinymce.urls')),

    url(r'^blog/', include('blog.urls',namespace='blog')),
    url(r'^videoapp/', include('videoapp.urls', namespace='videoapp')),
    url(r'^gkapp/', include('gk_app.urls', namespace='gk_app')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^jobs/', include('jobs.urls',namespace='jobs')),
    url(r'^question/', include('question_bank.urls',namespace='question_bank')),

    url(r'^api/', include('news.api.urls')),
    url(r'^api/blog/', include('blog.api.urls')),
    url(r'^api/jobs/', include('jobs.api.urls')),
    url(r'^api/video/', include('videoapp.api.urls')),

    url(r'^api/question/', include('question_bank.api.urls'))
]

gk_app/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from gk_app import views
app_name = "gk_app"
urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'create_blog/',views.create_blog),
    url(r'^$', views.home, name='home',),
    url(r'^categories/(?P<pk>\d+)/$', views.category_topics, name='category_topics'),
    url(r'^kkcate2/(?P<pk>\d+)/$', views.categoryWise_topics, name='category_topics2'),
    url(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.topic_posts, name='topic_posts'),
    url(r'^(?P<pk>\d+)/topics2/(?P<topic_pk>\d+)/$', views.topic_posts2, name='topic_posts2'),

    #url(r'^(?P<pk>\d+)/comment/(?P<topic_pk>\d+)/$', views.comment),
    url(r'^comment/$',views.comment),
    url(r'^tinymce/', include('tinymce.urls'))
]

gk_app/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.utils.text import Truncator
import datetime

class Date_Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    #description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey(Date_Category,on_delete=models.CASCADE, related_name='topics3')
    Publisher = models.ForeignKey(User,on_delete=models.CASCADE,related_name='topics3')

    def __str__(self):
        return self.subject


class DateWiseGK(models.Model):
    GK_Text = models.TextField(max_length=4000)
    title = models.CharField(max_length=200,blank=True)
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE, related_name='posts3')
    #created_at = models.DateTimeField(auto_now_add=True,blank=True)
    updated_at = models.DateTimeField(null=True,blank=True)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE, related_name='posts3',null=True,default="BodhiAI")
    #updated_by = models.ForeignKey(User,on_delete=models.CASCADE,null=True, related_name='+')
    link1 = models.URLField(null=True, blank=True)
    link2 = models.URLField(null=True, blank=True)
    link3 = models.URLField(null=True, blank=True)
    def __str__(self):
        return self.GK_Text
"""
class Comment(models.Model):

    user= models.ForeignKey(User,on_delete=models.CASCADE)

    comment= models.CharField(max_length=140, null=False)

    updated= models.DateTimeField(auto_now=True)

    timestamp= models.DateTimeField(auto_now_add=True)
    def _str__(self):
        return str(self.comment)
"""
class CategoryWise(models.Model):
    name = models.CharField(max_length=30, unique=True)
    #description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class TopicWise(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey(CategoryWise,on_delete=models.CASCADE, related_name='topics4')
    Publisher = models.ForeignKey(User,on_delete=models.CASCADE,related_name='topics4')

    def __str__(self):
        return self.subject


class CategoryWiseGK(models.Model):
    GK_Text = models.TextField(max_length=4000)
    title = models.CharField(max_length=200,blank=True)
    topic = models.ForeignKey(TopicWise,on_delete=models.CASCADE, related_name='posts4')
    #created_at = models.DateTimeField(auto_now_add=True,blank=True)
    updated_at = models.DateTimeField(null=True,blank=True,auto_now_add=True)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE, related_name='posts4',null=True,default="BodhiAI")
    #updated_by = models.ForeignKey(User,on_delete=models.CASCADE,null=True, related_name='+')
    link1 = models.URLField(null=True, blank=True)
    link2 = models.URLField(null=True, blank=True)
    link3 = models.URLField(null=True, blank=True)
    def __str__(self):
        return self.GK_Text

gk_app/forms.py
from django import forms
from gk_app.models import DateWiseGK,CategoryWiseGK

class DateWiseGKForm(forms.ModelForm):
    class Meta:
        model = DateWiseGK
        fields = "__all__"
class CategoryWiseGKForm(forms.ModelForm):
    class Meta:
        model =CategoryWiseGK
        fields = "__all__"

gk_app/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import get_object_or_404, render,redirect
from .models import *
import datetime
from .forms import DateWiseGKForm
from django.utils import timezone
def home(request):
    categories =Date_Category.objects.all().order_by('id').reverse()
    blogs = DateWiseGK.objects.all().order_by('updated_at').reverse()
    GK_categories=CategoryWise.objects.all().order_by('id').reverse()
    GK_blogs=CategoryWiseGK.objects.all().order_by('updated_at').reverse()
    return render(request,'gk_app/home.html', {'categories': categories,'blogs':blogs,'GK_categories': GK_categories,'GK_blogs':GK_blogs})

def category_topics(request, pk):
    category = get_object_or_404(Date_Category, pk=pk)
    topics = category.topics3.order_by('-last_updated')
    return render(request, 'gk_app/topics.html', {'category': category, 'topics': topics})
def categoryWise_topics(request, pk):
    category = get_object_or_404(CategoryWise, pk=pk)
    topics = category.topics4.order_by('-last_updated')
    GK_blogs = CategoryWiseGK.objects.all().order_by('updated_at').reverse()
    return render(request, 'gk_app/topics2.html', {'category': category, 'topics': topics ,'GK_blogs':GK_blogs})

def topic_posts(request, pk, topic_pk):
    topic =get_object_or_404(Topic, category__pk=pk, pk=topic_pk)
    topic.save()
    return render(request, 'gk_app/topic_posts.html', {'topic': topic})
def topic_posts2(request, pk, topic_pk):
    topic =get_object_or_404(TopicWise, category__pk=pk, pk=topic_pk)
    topic.save()
    print(topic)
    return render(request, 'gk_app/topic_posts2.html', {'topic': topic})



def create_blog(request):
    if request.method == "POST":
        form = DateWiseGKForm(request.POST)
        post = form.save()
        post.created_by = request.user
        post.updated_at = timezone.now()
        post.updated_by = request.user
        post.save()
        categories = Date_Category.objects.all()
        blogs = DateWiseGK.objects.all().order_by('updated_at')
        context ={'categories': categories,'blogs':blogs}
        return render(request,'gk_app/home.html',context)
    else:
        form = BlogForm()
    return render(request, 'gk_app/post_edit.html', {'form': form})

def comment(request):
    #comments = get_object_or_404(Comment, Blog__pk=pk, pk=Comment_pk)
    if request.method == 'POST':
        body = request.POST.get('body')
        user = User.objects.all()
        user = user[0]
        new_comment = Comment()
        new_comment.user = user
        new_comment.date = datetime.datetime.now()
        new_comment.comment = body
        new_comment.save()
        comments = Comment.objects.all().order_by('id').reverse()
        categories = Category.objects.all().order_by('id').reverse()
        blogs = Blog.objects.all().order_by('updated_at').reverse()
        context = {'comments': comments}
        return render(request,'gk_app/home.html',{'comments': comments,'categories': categories,'blogs':blogs})

        #return redirect('topic_posts', pk=pk, Comment_pk=Comment_pk)
    else:
        form = BlogForm()
    return render(request, 'gk_app/reply_topic.html', {'form': form})

gk_app/templates/gk_app/base.html
{% load static %}
<html>
  <head>
    <body>


<style>
  .header{
  background-color:#1abb9c;
  color: white;
  font-weight: 600;
}
  }




/* fixed social*/
#fixed-social {
   position: fixed;
   top: 500px;
   left:260px;
}

#fixed-social a {
   color: #fff;
   display: block;
   height: 40px;
   position: relative;
   text-align: center;
    line-height: 40px;
   width: 40px;
   margin-bottom: 1px;
   z-index: 2;
}
#fixed-social a:hover>span{
        visibility: visible;
  left: 41px;
  opacity: 1;
}
#fixed-social a span {
        line-height: 40px;
    left: 60px;
    position: absolute;
    text-align: center;
    width: 120px;

    visibility: hidden;
    transition-duration: 0.5s;
    z-index: 1;
    opacity: 0;
}
 .fixed-facebook{
        background-color: #00AAE5;
           padding: 10px;
 }
 .fixed-facebook span{
        background-color: #00AAE5;
        padding: 2px;
 }
 .fixed-twitter{
        background-color: #7D3895;
        padding: 10px;

 }
 .fixed-twitter span{
        background-color: #7D3895;
        padding: 2px;
 }
}
 .fixed-gplus{
        background-color: #00AF54;
        padding: 10px;

 }
 .fixed-gplus span{
        background-color: #00AF54;
        padding: 2px;
 }
 .fixed-linkedin{
        background-color: #FFC41E;
        padding: 10px;

 }
 .fixed-linkedin span{
        background-color: #FFC41E;
        padding: 2px;
 }
 .fixed-instagrem{
        background-color: #ED2B29;
        padding: 10px;

 }
 .fixed-instagrem span{
        background-color: #ED2B29;
        padding: 2px;
 }
 .fixed-tumblr{
        background-color: #EB1471;
        padding: 10px;

 }
 .fixed-tumblr span{
        background-color: #EB1471;
        padding: 2px;
 }
@import url('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css');

#social {
  margin: 20px 10px;
  text-align: center;
}

.smGlobalBtn { /* global button class */
    display: inline-block;
    position: relative;
    cursor: pointer;
    width: 50px;
    height: 50px;
    border:2px solid #ddd; /* add border to the buttons */
    box-shadow: 0 3px 3px #999;
    padding: 0px;
    text-decoration: none;
    text-align: center;
    color: #fff;
    font-size: 25px;
    font-weight: normal;
    line-height: 2em;
    border-radius: 27px;
    -moz-border-radius:27px;
    -webkit-border-radius:27px;
}





















</style>
     <link rel="icon" href="{% static 'gk_app/bodhi_logo.png'%}" type="image/gif" sizes="16x16">
     <link href="https://fonts.googleapis.com/css?family=" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <meta charset="utf-8">
    <title>{% block title %}BodhiAI Current Affairs {% endblock %}</title>
    <link href="{% static "tinymce/css/prism.css" %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'gk_app/img/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'gk_app/img/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'gk_app/img/css/app.css' %}">
    {% block stylesheet %}{% endblock %}
  </head>
  {% if user.is_authenticated %}
  <a href ="/create_blog/"></a>
  {% endif %}
  <body>
    {% block body %}

      <nav class="navbar navbar-expand-sm navbar-dark  header" style="background-color:orange">
        <div class="container">

          <a class="navbar-brand" href="http://13.127.54.121/">Bodhi AI Current Affairs </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="mainMenu">

              <ul class="navbar-nav ml-auto">
                <button type="button" class="btn btn-danger" style="height:auto ;">
                <a class="navbar-brand" href="http://bodhiaireact.s3-website.ap-south-1.amazonaws.com/#/userregistration">Join Now </a> </button>
                <li class="nav-item dropdown">
          <!--        <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		  
                    {{ user.username }}
                  </a> -->
                  </div>
                </li>
              </ul>
          </div>
        </div>
      </nav>

      <div class="container">
        <ol class="breadcrumb my-4">
          {% block breadcrumb %}
          {% endblock %}
        </ol>
        {% block content %}
        {% endblock %}
      </div>
    {% endblock body %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <style>

</style>

  <script src="https://code.jquery.com/jquery-3.1.1.min.js"
          integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
          crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
   <script src="{% static "tinymce/js/prism.js" %}"></script>


<div id="fixed-social" style= "position: fixed;top: 500px;left:260px;">
  <div>
    <a href="http://www.facebook.com/sharer/sharer.php?u=http://13.127.54.121/gkapp/" class="fixed-facebook" target="_blank"><i class="fa fa-facebook"></i> <span>Facebook</span></a>
  </div>
  <div>
    <a href="http://www.twitter.com/login/?url=http://13.127.54.121/gkapp/{{ request.get_full_path|urlencode }}" class="fixed-twitter" target="_blank"><i class="fa fa-twitter"></i> <span>Twitter</span></a>
  </div>
  <div>
    <a href="http://www.linkedin.com/shareArticle?url=http://13.127.54.121/gkapp/{{ request.get_full_path|urlencode }}&title=<Favourate Blog>&summary=<Blog>&source=www.bodhiai.in" class="fixed-linkedin" target="_blank"><i class="fa fa-linkedin"></i> <span>LinkedIn</span></a>
  </div>
  <div>
  <a href="#" class="fixed-instagrem" target="_blank"><i class="fa fa-instagram"></i> <span>Instagram</span></a>
  </div>
  <div>

  </div>

</div>





</body>
</html>

gk_app/templates/gk_app/create.html
<!DOCTYPE html>
<html>
<head>
<body>
{% load static %}
<div class="blog-header">
    <h3> Welcome To BodhiAI Platform </h3>
<br/>
</div>
</body>

<h4>Write Comments:
<body>

<form action="" method="POST">
    {% csrf_token %}
    <textarea rows="4" cols="50" size="5" maxlength="500" name="body">
    </textarea>
  <input type="submit"  value = "submit" name="blog_body" size="5" maxlength="500" placeholder=" Write Your Comment Here">
</form>
</body>
</html>

gk_app/templates/gk_app/home.html
{% extends 'gk_app/base.html' %}

{% load static %}
<head>
<link rel="icon" href="{% static 'gk_app/bodhi_logo.png'%}" type="image/gif" sizes="16x16">
    <style>


  }

</style>
<a href ="/CreateBlog/">New Blog</a>s
{% block breadcrumb %}
    <li  class="breadcrumb-item active"> <h3>Welcome to Bodhi AI</h3></li>
{% endblock %}

{% block content %}
    <body>

     <div class="col s3 simple" style="margin-left: px;padding-left:px;width: 26.66667%;">
         <div class="panel-title" style="max_width:100%;font-size:18px;color: inherit;background-color: black;font-family: 'Raleway', sans-serif;color: #fff;padding:10px ;  position: sticky; top: -10px;">Date Wise Current Affair</div>
         <div class="  " style="box-sizing: border-box;overflow-y: auto;max-height:400px;padding:10px; box-shadow: 1px 1px 1px 1px gray ; position: relative; ">



     {% for category in categories %}

      <div class="scrollbox" style="padding:10px; padding: 10px ; color: black ; border-bottom: solid #c5c0c0 1px;"> <a  class="scrollbox-content" style="padding-bottom:10px; margin-bottom: 5px ; text-decoration:none ; color:black;" href="{% url 'gk_app:category_topics' category.pk %}">{{category.name }} </a></div>

      {% endfor %}

</div>
<br><br>
              <div class="panel-title" style="max_width:100%;font-size:16px;color: inherit;background-color: #000000;font-family: 'Raleway', sans-serif;color: #fff;padding:10px ; margin-bottom: -8px ;  position: sticky; top: -10px;">Category Wise Current Affair</div>
  <div class="  "style="box-sizing: border-box;overflow-y: auto;max-height:400px;padding:10px; box-shadow: 1px 1px 1px 1px gray ; position: relative; ">
<!--     <div class="panel-title" style="max_width:100%;font-size:16px;color: inherit;background-color: #000000;font-family: 'Raleway', sans-serif;color: #fff;padding:10px ; margin-bottom: -8px ;  position: sticky; top: -10px;">Category Wise Current Affair</div>-->

</br>

     {% for c in GK_categories %}

      <div class=" scrollbox  " style="padding:10px; padding: 10px ; color: black ; border-bottom: solid #c5c0c0 1px;">  <a  class="scrollbox-content" style="padding-bottom:10px; margin-bottom: 5px ; text-decoration:none ; color:black;" href="{% url 'gk_app:category_topics2' c.pk %}">{{c.name }} </a></div>
        <small class="text-muted d-block">{{category.description }}  </small>

      {% endfor %}

    </div>

    </div>
</body>

{% for post in blogs %}

    <div class="card mb-2  border-dark" style="margin-top:25px;width: 70%;min-width: 350px;">
        <div class="  py-2 px-3 header" style="background-color:black" ><img src="{% static 'gk_app/bodhi_logo.png'%}" style="width:25px ; height:25px;border-radius: 100%;"alt="Avatar" ;> {{ post.updated_at.date }}
        </div>

        <div class="text">
        <div style= " border-radius: 50%;padding-left: 15%;">
        <!--    <img src="{% static 'bodhi_logo.png'%}" style="width:50px ; height:50px;border-radius: 100%;"alt="Avatar" ;>
        <div style="display: inline-block; margin:10px ">
        <div> {{ post.created_by }} </div>
            <div>   {{ post.updated_at.date }} </div>
            </div>-->
            </div>

            <div style="padding:10 25 0 25;color: #d63c24;font-size: 20px;line-height: normal;outline: medium none;text-decoration: none;">
         {{ post.title}}:
            </div>
            <div style="font-size:16; padding:5 25 0 25">
             <p>{{ post.GK_Text|safe}}</p>

            </p>
</div>







<!--
<div class="share">
        <a href="http://www.facebook.com/sharer/sharer.php?u=http://www.bodhiai.in/{{ request.build_absolute_uri }}"> <img src="https://www.duprelogistics.com/wp-content/themes/hightower_wp/images/Facebook.svg" height="40" width="30"></a>
    <a href="http://www.linkedin.com/shareArticle?url=http://www.bodhiai.in/membership/register/{{ request.get_full_path|urlencode }}&title=<Favourate Blog>&summary=<Blog>&source=www.bodhiai.in"><img src="https://sguru.org/wp-content/uploads/2018/02/Logo-LinkedIn-Round.png" height="28" width="20"></a>
        <a href="http://www.twitter.com/login/?url=http://www.bodhiai.in/membership/register/{{ request.get_full_path|urlencode }}"> <img src="https://carleton.ca/history/wp-content/uploads/twitter-logo-large.png" height="20" width="20"></a>
        <a href="https://www.whatsapp.com//share/post.php?url =http://www.bodhiai.in/membership/register/{{ request.get_full_path|urlencode }}" ><img src="https://pngimg.com/uploads/whatsapp/whatsapp_PNG12.png" height="25" width="20"></a>
    </div>
-->
    </div>
    </div>
  {% endfor %}


{% endblock %}

gk_app/templates/gk_app/post_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
<!DOCTYPE html>\
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>BodhiAI</title>
</head>
<body>


{% block content %}
    <form method="POST" class="post-form">{% csrf_token %}
         {{ form|crispy}}
    <button type="submit" class="btn btn-primary">Save</button>

    </form>
{% endblock %}
</body>
<style>


</style>
</html>

gk_app/templates/gk_app/reply_topic.html
{% extends 'base.html' %}
{% block content %}
    {% for post in comments %}
        <pre> by {{ post.user }}
            {{ post.comment}}</pre>
    {% endfor %}
{% endblock %}
</html

gk_app/templates/gk_app/topic_posts.html
{% extends './base.html' %}

{% load static %}

{% block title %}{{ topic.subject }}{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'gk_app:home' %}">Current Affairs</a></li>
  <li class="breadcrumb-item"><a href="{% url 'gk_app:category_topics' topic.category.pk %}">{{ topic.category.name }}</a></li>
  <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block content %}

  <div class="mb-4">
  </div>

  {% for post in topic.posts3.all %}


    <div class="card mb {% if forloop.first   %}border-dark{% endif %}">
        <div style="background-color:#000000" class="card-header text-white py-2 px-3">{{ post.topic }}  </div>
 <div style="padding:15 25 15 25;color: #d63c24;font-size: 20px;line-height: normal;outline: medium none;text-decoration: none;">
         {{ post.title}}:
            </div>
            <div style="font-size:16; padding:5 25 0 25">
             <p>{{ post.GK_Text|safe}}</p>

            </p>

          </div>
  {% endfor %}
{% endblock %}
<br>

gk_app/templates/gk_app/topic_posts2.html
{% extends 'gk_app/base.html' %}

{% load static %}

{% block title %}{{ topic.subject }}{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'gk_app:home' %}">Current Affairs</a></li>
  <li class="breadcrumb-item"><a href="{% url 'gk_app:category_topics2' topic.category.pk %}">{{ topic.category.name }}</a></li>
  <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block content %}

  <div class="mb-4">
  </div>

  {% for post in topic.posts4.all %}


    <div class="card mb-2 {% if forloop.first   %}border-dark{% endif %}">
        <div style="max_width:100%;font-size:16px;color: inherit;background-color:#000000;font-family: 'Raleway', sans-serif;color: #fff;padding:10px ; margin-bottom: -8px ;class="card-header text-white py-2 px-3">{{ post.topic }}</div>

     <div style="padding:15 25 15 25;color: #d63c24;font-size: 20px;line-height: normal;outline: medium none;text-decoration: none;">
         {{ post.title}}:
            </div>
            <div style="font-size:16; padding:5 25 0 25">
             <p>{{ post.GK_Text|safe}}</p>
            </p>

          </div>
  {% endfor %}
<br>
{% endblock %}

gk_app/templates/gk_app/topics.html
{% extends 'gk_app/base.html' %}

{% block title %}
  {{ category.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'gk_app:home' %}">Categories</a></li>
  <li class="breadcrumb-item active">{{ categoy.name }}</li>
{% endblock %}

{% block content %}


  <table class="table">
    <thead class="thead-inverse" style="background-color:#000000" >
      <tr >
        <th style="background-color:#000000">Topic</th>
        <th style="background-color:#000000">Publisher</th>
        <th style="background-color:#000000">Publish Date</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in topics %}
        <tr>
          <td><a href="{% url 'gk_app:topic_posts' category.pk topic.pk %}">{{ topic.subject }}</a></td>
          <td>{{ topic.Publisher.username }}</td>
          <td>{{ topic.last_updated }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

gk_app/templates/gk_app/topics2.html
{% extends 'gk_app/base.html' %}

{% block title %}
  {{ category.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'gk_app:home' %}">Categories</a></li>
  <li class="breadcrumb-item active">{{ categoy.name }}</li>
{% endblock %}

{% block content %}


  <table class="table">
    <thead class="thead-inverse"  style="background-color:#000000">
      <tr>
        <th style="background-color:#000000"> Topic</th>
        <th style="background-color:#000000"> Publisher</th>
        <th style="background-color:#000000"> Publish Date</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in topics %}
        <tr>
          <td><a href="{% url 'gk_app:topic_posts2' category.pk topic.pk %}">{{ topic.subject }}</a></td>
          <td>{{ topic.Publisher.username }}</td>
          <td>{{ topic.last_updated }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}